name: OpenAPI-Validator

on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  tests:
    name: OpenAPI Validator Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK 11
        uses: actions/setup-java@v5
        with:
            distribution: 'zulu' # See 'Supported distributions' for available options
            java-version: '11'
      - name: Run tests
        run: |
          mvn clean verify
  release:
    if: github.event.release.tag_name
    name: Release OpenAPI Validator
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v6
        with:
          ref: main
      - name: Set up JDK 11
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: 11
      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - name: Release prepare
        run: |
          git status
          mvn -B release:prepare
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: List current directory
        run: |
          ls -la
      - name: Release perform
        run: |
          mvn -B release:perform -Darguments="-Dmaven.deploy.skip=true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
